version: "3.8"

services:
  ledhat:
    image: ghcr.io/c4dt/led_hat:latest
    build: .
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ledhat.rule=Host(`hat.c4dt.org`)"
      - "traefik.http.routers.ledhat.entrypoints=websecure"
      - "traefik.http.routers.ledhat.tls.certresolver=myresolver"
      - "traefik.http.services.ledhat.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.ledhat.service=ledhat"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_traefik
